<?php if (count($errors) > 0): ?>
    <?php foreach ($errors as $messages): ?>
        <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?=array_keys($errors)[0]?>" role="alert"><?= $message ?></div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>
<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $id ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $date ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="<?=$router->urlFor('urls.check', ['id' => $id])?>">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <div>
            <table class="table table-bordered table-hover mt-2" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($checks as $check): ?>
                        <tr>
                            <td><?= $check->id?></td>
                            <td><?= $check->status_code?></td>
                            <td><?= $check->h1?></td>
                            <td><?= $check->title?></td>
                            <td><?= $check->description?></td>
                            <td><?= $check->created_at?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</main>