<?php if (count($errors) > 0): ?>
    <?php foreach ($errors as $message): ?>
        <div class="alert alert-danger" role="alert"><?= $message ?></div>
    <?php endforeach ?>
<?php endif ?>
<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>
                <form action="<?=$router->urlFor('urls.add')?>" method="post" class="d-flex justify-content-center">
                    <input type="text" name="url[name]" placeholder="https://www.example.com" value=""
                        class="form-control form-control-lg">
                    <input type="submit" class="btn btn-primary  btn-lg ms-3 px-5 text-uppercase mx-3"
                        value="Проверить">
                </form>
            </div>
        </div>
    </div>
</main>