<!DOCTYPE html>
<html lang="ru">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Third project for Hexlet.io">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <title>Анализатор страниц</title>
    </head>

    <body class="min-vh-100 d-flex flex-column">
        <header class="flex-shrink-0">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <div id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link " href="/urls">Сайты</a></li>
                    </ul>
                </div>
            </nav>
        </header>
        <?php if (count($errors) > 0): ?>
            <?php foreach ($errors as $message): ?>
                <div class="alert alert-danger" role="alert"><?= $message ?></div>
            <?php endforeach ?>
        <?php endif ?>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <h1>Сайты</h1>
                <div class="table-responsive">
                    <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Имя</th>
                                <th>Последняя проверка</th>
                                <th>Код ответа</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($urls as $url): ?>
                                <tr>
                                    <td><?= $url['id'] ?></td>
                                    <td>
                                        <a href="<?=$router->urlFor('renderUrlPage', ['id' => $url['id']])?>"><?= $url['name']?></a>
                                    </td>
                                    <td><?= $url['created_at']?></td>
                                    <td>{{status_code}}</td>
                                </tr>
                            <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </main>
        <footer class="border-top py-3 mt-5 flex-shrink-0">
            <div class="container-lg">
                <div class="text-center">
                    <a href="https://ru.hexlet.io/" target="_blank">Hexlet</a>
                </div>
            </div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    </body>

</html>